### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by exandi** [LoranKloeze/WhatsAllApp#1] opened 2017-05-17 09:42 UTC
Hey,
if I try to install your PlugIn for Chrome (Version 58.0.3029.110 (64-bit)) I get the follwing error Message:
"CRX_MAGIC_NUMBER_INVALID".

The Plugin isn't install and the Button doesn't appear obviously.

Regards

**Comment by LoranKloeze** [comment] 2017-05-17 10:04
Are you logged in?

**Comment by exandi** [comment] 2017-05-17 10:10
no i don't

**Comment by LoranKloeze** [comment] 2017-05-17 10:13
As far as I know, you'll need to be logged in for extensions outside the Chrome store to function.

**Comment by exandi** [comment] 2017-05-17 10:15
i logged in, restartet Chrome and still get the same Errormessage.

**Comment by LoranKloeze** [comment] 2017-05-17 10:17
Ok, let's park this for a few moments. It's important for me to find out if this is an error in this extension or it has something to do with your environment. 

Any other people having the same problems: please reply in this thread and tell me your Chrome version + OS.

**Comment by gr4ssi** [comment] 2017-05-17 11:25
Hi, here is how to get it running:
Not logged in to Google, Go to Settings, Extensions. Activate Developer-Mode.
Assuming, you now have the extension installed (and it got deactivated):
Go to C:\Users\YourUserName\AppData\Local\Google\Chrome\User Data\Default\Extensions\cryptic-letters\
Copy the relevant folder to somewhere else.
It should be the name 0.0.0_0 or something.
Remember where you put it!
Then go to "Load unpacked extension" (See 3rd in screenshot).
![grafik](https://cloud.githubusercontent.com/assets/19840345/26151662/1bb57d20-3b04-11e7-9159-262ae74ade7c.png)

You need to get to run https://web.whatsapp.com/ also.

If all works, it looks like this:

![grafik](https://cloud.githubusercontent.com/assets/19840345/26151731/5501884e-3b04-11e7-8ae4-e6fd65dab6f9.png)

**Comment by LoranKloeze** [comment] 2017-05-17 11:29
Thx, unpacked extensions will always load as long as there are no errors in the manifest. I created the packed version so people can just drag/drop it in Chrome. Apparently it doesn't always work that way.

**Comment by Schweng** [comment] 2017-05-17 11:32
Extension works as long as you dont restart chrome. After restart the extension is deactivated. With gr4ssis workaround it works even with restart

**Comment by gr4ssi** [comment] 2017-05-17 11:32
Ah wait, you got it wrong otherwise. I had the same error.
If you go to:
![grafik](https://cloud.githubusercontent.com/assets/19840345/26151849/db65201c-3b04-11e7-8bd3-dffaad9e1788.png)

and download it there, it won't work. You have to click on "WhtatsAllApp.crx", then click on Download:
![grafik](https://cloud.githubusercontent.com/assets/19840345/26151915/1cad9478-3b05-11e7-879c-17674e243ab7.png)

Otherwise, you are just saving and installing a github html page, which obviously will not work.

Afterwards, proceed with the above guide (from me ;-) )

**Comment by gr4ssi** [comment] 2017-05-17 11:32
ah okay. I first tried installing the git hub html page, which didn't work. ;-)

**Comment by LoranKloeze** [comment] 2017-05-17 11:33
Ah! There we are. I'll include that instruction in the readme. Thanks!

**Comment by gr4ssi** [comment] 2017-05-17 11:34
welcome. glad I could help. Gave me a bit of a headache to get it to run... nice project!

**Comment by LoranKloeze** [comment] 2017-05-17 11:37
I'll close it for now since changes are the TS's problems are solved by clicking Download at the .crx file.

**Comment by gr4ssi** [comment] 2017-05-17 11:39
no, It was resolved by the developer-option. You misread the solution, I guess.

**Comment by gr4ssi** [comment] 2017-05-17 11:40
This was, what solved it for him:
https://github.com/LoranKloeze/WhatsAllApp/issues/1#issuecomment-302061768

**Comment by LoranKloeze** [comment] 2017-05-17 11:44
Well, I could reproduce TS's error message. And by using Download it works by just drag/drop instead of having to use the unpacked way. So, I would say it is solved by your solution :)

**Comment by gr4ssi** [comment] 2017-05-17 11:51
yes loran, but I provided two solutions. The first was, what fixed it for Scheng, and the second was what I needed to do, then I needed my other solution, which I posted in this thread before.
I posted to things here, in reverse order. 
The hazzle is, chrome deactivates your extension, if you don't go to developer mode and manually add it.
Cheers, 
Marcus

**Comment by gr4ssi** [comment] 2017-05-17 11:53
what I'm saying (trying to) is, if you don't enable "developer mode" in extensions, you can't propperly use it because it gets disabled after restart.

**Comment by LoranKloeze** [comment] 2017-05-17 11:54
Alright, I get it. I'm trying to think of a solution where people don't have to install it unpacked. I'll test some more.

**Comment by gr4ssi** [comment] 2017-05-17 11:57
I think unpacked would be good, actually:
you make/provide a Zip-file, tell user to enable developer mode, let him/her load unpacked zip-folder into chrome. Easy as pie ;-)

**Comment by LoranKloeze** [comment] 2017-05-17 11:57
Or I could pay up the 5 bucks and put it in the store :D

**Comment by gr4ssi** [comment] 2017-05-17 11:59
hm, but you're Dutch. That won't work. :-P

**Comment by gr4ssi** [comment] 2017-05-17 12:00
you could do crowdfunding, though. ;-)

**Comment by LoranKloeze** [comment] 2017-05-17 12:08
Ha, that's always a possibility. I've changed the install instructions to use the unpacked version.

**Comment by gr4ssi** [comment] 2017-05-17 12:09
Just checked the new instructions: I think it will be much easier like this. Less frustrating.

**Comment by LoranKloeze** [comment] 2017-05-17 12:10
Everybody wins. Thanks for your advice!

**Closed by LoranKloeze** 2017-05-17 12:10 UTC
